import type { BatchRecord } from "./batch-types";

const NOW = new Date("2026-05-19T10:00:00Z");

function hoursAgo(h: number): Date {
  return new Date(NOW.getTime() - h * 3_600_000);
}

function hoursFromNow(h: number): Date {
  return new Date(NOW.getTime() + h * 3_600_000);
}

export const BATCH_RECORDS: BatchRecord[] = [
  {
    id: "BT-20260519-01",
    submittedAt: hoursAgo(6),
    etaAt: hoursFromNow(18),
    garments: 12,
    protocol: "sterilize",
    pickupLocationId: "icu-west-4",
    pickupLabel: "ICU — West Wing Level 4",
    surchargeCents: 1920,
    hazardEnabled: false,
    hasReceipt: false,
    stage: "in-transit",
    lastStageAt: hoursAgo(4),
  },
  {
    id: "BT-20260519-02",
    submittedAt: hoursAgo(10),
    etaAt: hoursAgo(1.5), // delayed — ETA passed 1.5h ago
    garments: 8,
    protocol: "sanitize",
    pickupLocationId: "or-main-3",
    pickupLabel: "Main OR — Level 3",
    surchargeCents: 0,
    hazardEnabled: false,
    hasReceipt: false,
    stage: "at-cleaner",
    lastStageAt: hoursAgo(8),
  },
  {
    id: "BT-20260519-03",
    submittedAt: hoursAgo(4),
    etaAt: hoursFromNow(8),
    garments: 24,
    protocol: "standard",
    pickupLocationId: "er-east-1",
    pickupLabel: "Emergency Dept — East Level 1",
    surchargeCents: 0,
    hazardEnabled: false,
    hasReceipt: false,
    stage: "picked-up",
    lastStageAt: hoursAgo(3.5),
  },
  {
    id: "BT-20260519-04",
    submittedAt: hoursAgo(28),
    etaAt: hoursFromNow(2),
    garments: 6,
    protocol: "sterilize",
    pickupLocationId: "icu-west-4",
    pickupLabel: "ICU — West Wing Level 4",
    surchargeCents: 960,
    hazardEnabled: true,
    hasReceipt: true,
    stage: "quality-check",
    lastStageAt: hoursAgo(2),
  },
  {
    id: "BT-20260518-07",
    submittedAt: hoursAgo(36),
    etaAt: hoursFromNow(4),
    garments: 18,
    protocol: "sanitize",
    pickupLocationId: "peds-west-2",
    pickupLabel: "Pediatrics — West Wing Level 2",
    surchargeCents: 0,
    hazardEnabled: false,
    hasReceipt: false,
    stage: "out-for-delivery",
    lastStageAt: hoursAgo(1),
  },
  {
    id: "BT-20260518-08",
    submittedAt: hoursAgo(48),
    etaAt: hoursAgo(2), // delayed — ETA passed 2h ago
    garments: 14,
    protocol: "standard",
    pickupLocationId: "er-east-1",
    pickupLabel: "Emergency Dept — East Level 1",
    surchargeCents: 0,
    hazardEnabled: false,
    hasReceipt: false,
    stage: "out-for-delivery",
    lastStageAt: hoursAgo(10),
  },
  {
    id: "BT-20260519-05",
    submittedAt: hoursAgo(3),
    etaAt: hoursFromNow(21),
    garments: 30,
    protocol: "standard",
    pickupLocationId: "admin-5",
    pickupLabel: "Admin Offices — Level 5",
    surchargeCents: 0,
    hazardEnabled: false,
    hasReceipt: false,
    stage: null, // partner hasn't updated
    lastStageAt: undefined,
  },
  {
    id: "BT-20260519-06",
    submittedAt: hoursAgo(8),
    etaAt: hoursFromNow(4),
    garments: 5,
    protocol: "sterilize",
    pickupLocationId: "or-main-3",
    pickupLabel: "Main OR — Level 3",
    surchargeCents: 600,
    hazardEnabled: false,
    hasReceipt: false,
    stage: "at-cleaner",
    lastStageAt: hoursAgo(5),
  },
  {
    id: "BT-20260519-07",
    submittedAt: hoursAgo(5),
    etaAt: hoursFromNow(7),
    garments: 9,
    protocol: "sanitize",
    pickupLocationId: "peds-west-2",
    pickupLabel: "Pediatrics — West Wing Level 2",
    surchargeCents: 0,
    hazardEnabled: false,
    hasReceipt: false,
    stage: "in-transit",
    lastStageAt: hoursAgo(3),
  },
  {
    id: "BT-20260518-09",
    submittedAt: hoursAgo(32),
    etaAt: hoursAgo(0.5), // delayed — ETA passed 30 min ago (>1h threshold not met, but use for testing)
    garments: 22,
    protocol: "standard",
    pickupLocationId: "icu-west-4",
    pickupLabel: "ICU — West Wing Level 4",
    surchargeCents: 0,
    hazardEnabled: false,
    hasReceipt: false,
    stage: "out-for-delivery",
    lastStageAt: hoursAgo(6),
  },
  {
    id: "BT-20260519-08",
    submittedAt: hoursAgo(2),
    etaAt: hoursFromNow(10),
    garments: 7,
    protocol: "standard",
    pickupLocationId: "er-east-1",
    pickupLabel: "Emergency Dept — East Level 1",
    surchargeCents: 0,
    hazardEnabled: false,
    hasReceipt: false,
    stage: "picked-up",
    lastStageAt: hoursAgo(1.5),
  },
  {
    id: "BT-20260519-09",
    submittedAt: hoursAgo(44),
    etaAt: hoursAgo(1),
    completedAt: hoursAgo(0.5),
    garments: 11,
    protocol: "sanitize",
    pickupLocationId: "peds-west-2",
    pickupLabel: "Pediatrics — West Wing Level 2",
    surchargeCents: 0,
    hazardEnabled: false,
    hasReceipt: false,
    stage: "delivered",
    lastStageAt: hoursAgo(0.5),
  },
];
